services:
  - type: worker
    name: sentinela-daily-worker
    region: ohio
    runtime: python
    buildCommand: pip install -r requirements.txt
    runCommand: python worker_sentinela.py
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: IG_USERNAME
        value: monitoramento.discurso
      - key: IG_PASSWORD
        sync: false
      - key: GROQ_API_KEY
        sync: false
