import simpleGit, { type SimpleGit } from "simple-git";
import { execCommand } from "../providers/base.js";
import { readFile } from "node:fs/promises";
import { existsSync, readdirSync } from "node:fs";
import { join } from "node:path";

export interface PRDescription {
        title: string;
        body: string;
}

/**
 * Generate a PR description from session artifacts
 */
export async function generatePRDescription(
        sessionDir: string,
        branchName: string,
        baseBranch: string
): Promise<PRDescription> {
        let prdContent = "";
        let ticketSummaries: string[] = [];

        // Try to read PRD
        const prdPath = join(sessionDir, "prd.md");
        if (existsSync(prdPath)) {
                try {
                        prdContent = await readFile(prdPath, "utf-8");
                } catch {}
        }

        // Extract title from PRD (first heading)
        let title = "Pickle Rick Session Changes";
        const titleMatch = prdContent.match(/^#\s+(.*)$/m);
        if (titleMatch) {
                title = titleMatch[1].replace(/\s+PRD$/i, "").trim();
        }

        // Gather ticket summaries from implementation docs
        try {
                const entries = readdirSync(sessionDir, { withFileTypes: true });
                for (const entry of entries) {
                        if (entry.isDirectory() && !entry.name.startsWith(".") && entry.name !== "debug") {
                                const ticketDir = join(sessionDir, entry.name);
                                const implPath = join(ticketDir, "implementation.md");
                                const ticketPath = join(ticketDir, `linear_ticket_${entry.name}.md`);

                                let ticketTitle = entry.name;
                                if (existsSync(ticketPath)) {
                                        try {
                                                const ticketContent = await readFile(ticketPath, "utf-8");
                                                const ticketTitleMatch = ticketContent.match(/^#\s+(.+)$/m);
                                                if (ticketTitleMatch) ticketTitle = ticketTitleMatch[1];
                                        } catch {}
                                }

                                if (existsSync(implPath)) {
                                        try {
                                                const implContent = await readFile(implPath, "utf-8");
                                                // Extract summary section or first few lines
                                                const summaryMatch = implContent.match(/##\s*Summary\s*\n([\s\S]*?)(?=\n##|$)/i);
                                                const summary = summaryMatch
                                                        ? summaryMatch[1].trim().slice(0, 500)
                                                        : implContent.slice(0, 300).trim();
                                                ticketSummaries.push(`### ${ticketTitle}\n${summary}`);
                                        } catch {}
                                }
                        }
                }
        } catch {}

        // Extract key sections from PRD for the body
        let problemStatement = "";
        let objective = "";
        const problemMatch = prdContent.match(/##\s*Problem Statement\s*\n([\s\S]*?)(?=\n##|$)/i);
        if (problemMatch) problemStatement = problemMatch[1].trim();
        const objectiveMatch = prdContent.match(/##\s*Objective.*?\n([\s\S]*?)(?=\n##|$)/i);
        if (objectiveMatch) objective = objectiveMatch[1].trim();

        // Build PR body
        const body = `## Summary

${problemStatement ? `**Problem:** ${problemStatement.split('\n')[0]}` : 'Automated changes from Pickle Rick session.'}

${objective ? `**Objective:** ${objective.split('\n')[0]}` : ''}

## Changes

${ticketSummaries.length > 0 ? ticketSummaries.join('\n\n') : 'See commit history for details.'}

## Test Plan

- [ ] Review code changes
- [ ] Run tests locally
- [ ] Verify functionality

---

🥒 Generated by [Pickle Rick CLI](https://github.com/anthropics/pickle-rick)

**Branch:** \`${branchName}\` → \`${baseBranch}\`
`;

        return { title, body };
}

/**
 * Push a branch to origin
 */
export async function pushBranch(branch: string, workDir = process.cwd(), gitInstance?: SimpleGit): Promise<boolean> {
        const git: SimpleGit = gitInstance || simpleGit(workDir);

        try {
                await git.push("origin", branch, ["--set-upstream"]);
                return true;
        } catch {
                return false;
        }
}

/**
 * Create a pull request using gh CLI
 */
export async function createPullRequest(
        branch: string,
        baseBranch: string,
        title: string,
        body: string,
        draft = false,
        workDir = process.cwd(),
        gitInstance?: SimpleGit
): Promise<string | null> {
        // Push branch first
        const pushed = await pushBranch(branch, workDir, gitInstance);
        if (!pushed) {
                return null;
        }

        // Build gh pr create command args
        const args = [
                "pr",
                "create",
                "--base",
                baseBranch,
                "--head",
                branch,
                "--title",
                title,
                "--body",
                body,
        ];

        if (draft) {
                args.push("--draft");
        }

        // Execute gh CLI
        const { stdout, exitCode } = await execCommand("gh", args, workDir);

        if (exitCode !== 0) {
                return null;
        }

        // Return the PR URL (gh outputs the URL on success)
        return stdout.trim() || null;
}

/**
 * Check if gh CLI is available and authenticated
 */
export async function isGhAvailable(): Promise<boolean> {
        try {
                const { exitCode } = await execCommand("gh", ["auth", "status"], process.cwd());
                return exitCode === 0;
        } catch {
                return false;
        }
}

/**
 * Get the remote URL for origin
 */
export async function getOriginUrl(workDir = process.cwd(), gitInstance?: SimpleGit): Promise<string | null> {
        const git: SimpleGit = gitInstance || simpleGit(workDir);

        try {
                const remotes = await git.getRemotes(true);
                const origin = remotes.find((r) => r.name === "origin");
                return origin?.refs?.fetch || null;
        } catch {
                return null;
        }
}
